name: 🐞 Bug report
description: Report a very clearly broken issue.
title: 'bug: <title>'
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # ReVanced Extended bug report

        Important to note that your issue may have already been reported before. Please check for existing issues [here](https://github.com/inotia00/ReVanced_Extended/labels/bug).
  - type: dropdown
    attributes:
      label: Type
      options:
        - Error while patching
        - Error at runtime
        - Cosmetic
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Tools used
      options:
        - ReVanced Manager
        - rvx-builder
        - Revancify
        - CLI
    validations:
      required: true
  - type: textarea
    attributes:
      label: Application
      description: Write down the application and version where the issue occurs.
      placeholder: e.g. YouTube v18.16.39
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug description
      description: How did you find the bug? Any additional details that might help?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Add the steps to reproduce this bug.
      placeholder: Step 1. include `hide-video-ads` and patch. Step 2. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or videos
      description: Add screenshots or videos that show the bug here.
      placeholder: Drag and drop the screenshots/videos into this box.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Device Environment
      description: Add your device environment.
      placeholder: Android 13, MIUI 14 ...
    validations:
      required: false
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new and no duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I filled out all of the requested information in this issue properly.
          required: true
        - label: I have written the title and contents in English.
          required: true
        - label: This issue does not reproduce on unpatched YouTube or YT Music.
          required: true